spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/studs
    username: s368420
    password: SGm3njJqt6YZ5Jmh
  jpa:
    open-in-view: true
    show-sql: true
jwt:
  secret-key: 812af4d7c69835cdd20d0dc236ad7e9f00aa31126f0ab650d990b9b9b2d1b0ba
  expiration-time: 86400000